# defaults
http://localhost:46704
--
--
# takes query, files, timeout
POST /
{
  "query": {
    "type": "properties",
    "file": "/home/nilsb/tmp/x/index.js",
    "end": {
      "line": 6,
      "ch": 8
    }
  }
}

