" Keep undo history after closing a file
set undofile
let &undodir = g:vim.var.dir . "undo"
call Mkdir(&undodir, "p")

" nomodeline can not be revered by plugins
" but modeline is needed by dbext even though it uses its own parser.
set nomodeline

augroup MyVimrcAugroupOnlySetCurrentDirAsPath
  autocmd!
  autocmd VimEnter * set path=,,
augroup END

" Make helpgrep find vim's own help files before plugin help files
let &runtimepath = '/usr/share/nvim/runtime,'
      \ . &runtimepath

execute "set runtimepath+=" . g:vim.etc.dir
execute "set runtimepath+=" . g:vim.after.dir

" Reload vimrc on write
" autocmd BufWritePost vimrc source $MYVIMRC
" nnoremap <leader>vr :execute "source " . $MYVIMRC<cr>

" NetRW
" Detail View
let g:netrw_liststyle = 1
" Human-readable file sizes
let g:netrw_sizestyle = "H"
" hide dotfiles
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'
" hide dotfiles by default
let g:netrw_hide = 1
" Turn off banner
" let g:netrw_banner = 0
" Prevent creation of .netrwhist file
let g:netrw_dirhistmax = 0
" Use gx to open any file under cursor in appropriate app
let g:netrw_browsex_viewer="xdg-open"
nnoremap <leader>E :Explore<cr>

if $DISPLAY != ''
  " Make the clipboard register the same as the default register
  " this allows easy copy to other x11 apps
  set clipboard=unnamed,unnamedplus
endif

" Chdir to the dir of the current buffer
" set autochdir
" autocmd BufEnter * silent! execute "lcd %:p:h:gs/ /\\ /

" A history of ":" commands, and a history of previous search patterns
set history=1000

" Show line numbers
" set number
" Relative line numbers
" set relativenumber

" allow the cursor to pass the last character
" set virtualedit=all

" Set reload a file when it is changed from the outside
set autoread

" Automatically write file if leaving a buffer
set autowriteall

" Leave cursor where it was - even on page jump
set nostartofline

let &tabstop = 2
let &softtabstop = &tabstop
let &shiftwidth = &tabstop
set shiftround
set smarttab
set expandtab

" automatically indent to match adjacent lines
set autoindent

" textformattting
set textwidth=80

" Note: if the listpat fits in the previous row the listpat is wrapped into the
" previous row

" TODO: needs work
" SEE ALSO: https://www.reddit.com/r/vim/comments/4lvaok/supercharge_vim_formatting_for_plain_text/
" " These seem to get overwritten by too many plugins
" function! MyVimrcForceFormattingSettings() abort
"   setlocal formatoptions=roqanj1c
"   let &formatlistpat = '\c\v^\s*[-\+\*]\s+'
"   let &formatlistpat .= '|\c\v^\s*(todo|note|tags|see also|fix)\s+'
"   setlocal noautoindent
" endfunction
" augroup MyVimrcAugroupForceFormattingSettings
"   autocmd!
"   autocmd BufWinEnter * call MyVimrcForceFormattingSettings()
" augroup END

" see also:
" :h auto-format
function! MyVimrcShowFormatSettings() abort
  call INFO('&comments:', &comments)
  call INFO('&commentstring:', &commentstring)
  call INFO('&formatoptions:', &formatoptions)
  call INFO('&formatlistpat:', &formatlistpat)
  call INFO('&autoindent:', &autoindent)
  call INFO('&smartindent:', &smartindent)
  call INFO('&cindent:', &cindent)
  " call INFO('g:MyMarkdownFormatoptions:', g:MyMarkdownFormatoptions)
endfunction

set backspace=indent,start

set splitbelow

" Line wrapping
set wrap

" Stay in the middle of the screen
set scrolloff=999
" set sidescrolloff=0

" Scroll by one char at end of line
" set sidescroll=1

" None of these are word dividers
set iskeyword+=_,$,@,%,#,-

" Don't make noise
set noerrorbells
set novisualbell
set t_vb=

" assume fast terminal connection
set ttyfast

set hidden
" set winheight=9999

" only show 1 line for minimized windows
" set winminheight=0

" Set preview window height
" set previewheight=99

augroup MyVimrcAugroupMaximizeHelp
  autocmd!
  autocmd BufEnter * :if &buftype == 'help' | only | endif
augroup END

augroup MyVimrcAugroupListAllBuffers
  autocmd!
  autocmd BufEnter * :setlocal buflisted
augroup END

" show count of selected lines / columns
set showcmd

" Make macros render faster (lazy draw)
" set lazyredraw

set display=lastline,uhex

" Vim will wrap long lines at any character in 'breakat'
set linebreak
set breakat&vim
if IsNeoVim()
  set breakindent
  let &showbreak="  ↪ "
  " let &showbreak="  "
else
  let &showbreak=repeat(' ', &tabstop * 2) . "↪ "
endif

set mousehide
set mouse=

" always assume decimal numbers
set nrformats-=octal

set isfname-==

command! -nargs=* RemoveTrailingSpaces :silent %s/\s\+$//e
command! -nargs=* RemoveNewlineBlocks
      \ :silent %s/\v\s*\n(\s*\n)+/\r\r/g
      \ | :silent %s/\n*\%$//g

" Deactivate gui cursor to fix nvim regression (2017-07-25)
" (https://github.com/neovim/neovim/issues/7049)
set guicursor=

"### Undo and swap

" Maximum amount of memory in Kbyte to use for all buffers together.
set maxmemtot=2048

" Never create backup files
set nobackup
set nowritebackup

" Never create swapfiles
set noswapfile

"### Timeouts

" Timeout on mappings and key codes (faster escape etc)
" set timeout
" set timeoutlen=300
" set ttimeoutlen=10

" used for the CursorHold autocommand event
set updatetime=1000

set suffixesadd=.txt,.md

" don't echo make output to screen
let &shellpipe = '&>'

" turn off folding
set nofoldenable

"### Mappings

" For a list of vim's internal mappings see:
" :h index

" Potentially reassignable keys for normal mode:
" s, S, Q, Z, <bs>, M, m, r, R, <space>, Y
" <cr> is used in quickfix etc for jumping
" Maybe use r as secondary leader?

" Possible insert mode leaders:
" imap <c-b>
" imap <c-space>

" These are the same for vim
" Tab and Ctrl-I (<c-i><c-I>)
" Enter and Ctrl-M (<c-m>)
" Esc and Ctrl-[ (<c-[>)

" Clear all mappings
" :mapclear

" Map space to leader instead of the other way around to keep the original
" leader in insert mode - because space does not work well there.
nmap <space> <leader>
vmap <space> <leader>

" Ignore the leader if the following key is not mapped
nmap <leader> <nop>
vmap <leader> <nop>

" also use <space> for custom text-objects - i.e. see: vim-textobj-lastpat.vim

nnoremap <leader>vee :call VimEnvironment()<cr><esc>
nnoremap <leader>veg :call DUMP(g:)<cr>

" use saner regexes
" TODO checkout bundle 'vim-scripts/eregex.vim'
nnoremap :s/ :s/\V

nnoremap <c-z> :silent wall<cr><c-z>
inoremap <c-z> <esc>:silent wall<cr><c-z>

" Switch to alternative file
" nnoremap <BS> <C-^>

" Save file as root
command! -nargs=* WW :SudoWrite

" Adding a left shift key does not work like this
" nnoremap < <shift>

" Does not work on terminal vim
" nnoremap <s-space> <C-b>

" TODO: exclude :explore buffers
nmap <silent>L :bnext<cr>
nmap <silent>H :bprev<cr>

" use <leader>! as prefix to remap stuff
" Remap <C-i> as it's the same as Tab
" nnoremap <leader>!a <C-o>
" nnoremap <leader>!b <C-i>

nnoremap <c-o> <c-i>
nnoremap <c-u> <c-o>

" Write all when leaving a tmux pane
nmap <silent><c-j> :silent wall<cr><c-j>
nmap <silent><c-k> :silent wall<cr><c-k>
nmap <silent><c-h> :silent wall<cr><c-h>
nmap <silent><c-l> :silent wall<cr><c-l>

imap <c-h> <esc><c-h>
imap <c-l> <esc><c-l>
imap <c-j> <esc><c-j>
imap <c-k> <esc><c-k>

vmap <c-h> <esc><c-h>
vmap <c-l> <esc><c-l>
vmap <c-j> <esc><c-j>
vmap <c-k> <esc><c-k>

nnoremap <silent> <leader>go :only<cr>

" Never use formatprg (it's global) and doesn't fallback to vim's default
set formatprg=false

" Nicer redo
" tags: undo
nnoremap U <c-r>
nnoremap <leader>gu U

" Dont use Q for Ex mode
nnoremap Q :xa<cr>

" Yank from the cursor to the end of the line, to be consistent with C and D.
nnoremap Y y$

" make . work with visually selected lines
xnoremap . :norm.<CR>

" Remap set mark because m is used by easyclip
nnoremap <leader>m m
nnoremap M '

" Quickly jump to buffers
nnoremap <nowait>gb :ls<cr>:buffer<space>

nnoremap <silent><leader>if :!firefox
      \ "https://duckduckgo.com/?q=<cword> site:stackoverflow.com"<cr><cr>
vnoremap <silent><leader>if y:execute '!firefox '
      \ . 'https://duckduckgo.com/?q=' . @"<cr>
nnoremap <silent><leader>is :execute
      \ ":RunIntoBuffer so-lucky ". expand("<cword>") . " [" . &filetype . "]"<cr>

" Run current line in the shell
nnoremap <silent><leader>el :RunCursorLine<cr>

" Don't wait after escape in insert mode
" Breaks curser keys etc. (apparently not in Neovim)
" removed from Neovim (2017-03-01)
" set noesckeys

" Close buffer
" Mapping <esc> in vimrc breaks arrow behaviour"
" (http://stackoverflow.com/questions/11940801)
" - seems to be no problem with neovim
nnoremap <silent><esc> :call BufferClose()<cr>

" Causes delay
" nnoremap <esc>[ <esc>[

" Open command-line window
" :h cmdline-window
nnoremap <space><space> q:i
vnoremap <space><space> q:i
nnoremap <leader>k q:i<esc>k
nnoremap <leader>A q:i<esc>kA

augroup MyVimrcAugroupAdjustWindowSizes
  autocmd VimEnter,VimResized * :let &cmdwinheight = &lines / 5
  autocmd VimEnter,VimResized * :execute 'nnoremap rl ' . &columns / 2 . 'l'
  autocmd VimEnter,VimResized * :execute 'nnoremap rh ' . &columns / 2 . 'h'
  autocmd VimEnter,VimResized * :execute 'nnoremap rj ' . (&lines / 2 - 3) . 'j'
  autocmd VimEnter,VimResized * :execute 'nnoremap rk ' . (&lines / 2 - 3) . 'k'
augroup END

augroup MyVimrcAugroupCmdwinSetup
  autocmd!
  " Reset <cr> mapping for command-line-window in case <cr> is mapped somewhere
  autocmd CmdwinEnter * nnoremap <buffer> <cr> <cr>

  " autocmd CmdwinEnter * inoremap <buffer><silent> <tab> <esc>:quit<cr>
  autocmd CmdwinEnter * nnoremap <buffer><silent> <tab> :quit<cr>

  autocmd CmdwinEnter * nmap <buffer><silent> <c-h> :quit<cr><c-h>
  autocmd CmdwinEnter * nmap <buffer><silent> <c-j> :quit<cr><c-j>
  autocmd CmdwinEnter * nmap <buffer><silent> <c-k> :quit<cr>
  autocmd CmdwinEnter * nmap <buffer><silent> <c-l> :quit<cr><c-l>

  autocmd CmdwinEnter * nmap <buffer><silent> <leader>k :quit<cr>

  autocmd CmdwinEnter * imap <buffer><silent> <c-h> <esc>:quit<cr><c-h>
  autocmd CmdwinEnter * imap <buffer><silent> <c-j> <esc>:quit<cr><c-j>
  autocmd CmdwinEnter * imap <buffer><silent> <c-k> <esc>:quit<cr>
  autocmd CmdwinEnter * imap <buffer><silent> <c-l> <esc>:quit<cr><c-l>
augroup END

" Reselect visual block after indent
vnoremap <nowait>< <gv
vnoremap <nowait>> >gv

" hide annoying quit message
" nnoremap <C-c> <C-c>:echo<cr>

" always search forward and N backward, use this
" nnoremap <expr> n 'Nn'[v:searchforward]
" nnoremap <expr> N 'nN'[v:searchforward]

nmap <leader>?? <leader>vr
nnoremap <leader>vr :execute "edit " . g:vim.etc.dir . "/README.md"<cr>
nnoremap <leader>vv :execute "edit " . g:vim.etc.dir . "after/vimrc"<cr>
nnoremap <silent> <leader>vt :execute "edit " . g:vim.etc.dir
      \ . '/after/ftplugin/' . &filetype . '.vim'<cr>

command! -nargs=* EditInBufferDir
      \ :execute 'edit ' . expand('%:p:h') . '/' . expand('<args>')

" Show all <leader> mappings
nnoremap <leader>vm :Verbose map <leader><cr> <bar> :only<cr>

" Show all <leader> search mappings
nnoremap <leader>/? :Verbose map <leader>/<cr> <bar> :only<cr>

" open search history and select last entry
nnoremap <leader>// q/k

" search for selection
" vnoremap <leader>// y:execute '/' . @"<cr>
vnoremap <leader>// y:/\V<c-r>"<cr>
nnoremap <leader>/C /\v^\s*[/"#]+<cr>
" nnoremap <leader>/b /^.*\S\+\s\+{\s*$<cr>
nnoremap <leader>/b /^.*{.*$<cr>
nnoremap <leader>/S /^\S\+<cr>
nnoremap <leader>/w /\<\><left><left>
nnoremap <leader>/r gg/require<cr>}
nnoremap <leader>/t gg/TODO<cr>
" nnoremap ( ?[\[({<]<cr>
" nnoremap ) /[\[({<]<cr>
nnoremap ( :normal F{<cr>
nnoremap ) :normal f{<cr>
" nnoremap ) ?[\])}>]<cr>

" nnoremap [[ ?{<cr>
" nnoremap ]] /{<cr>

nnoremap <silent> <leader>vt :execute ':edit ' \ . fnameescape(g:vim.after.dir . 'ftplugin/' . &filetype . '.vim')<cr>

" Make gf work with relative file names and non existent files
nnoremap <leader>gf :execute ":edit " . expand('%:h') . '/' . expand('<cfile>')<cr>

nnoremap ' `
nnoremap ` '

" Restore cursor position after visual selection
nnoremap v m`v
nnoremap V m`V
nnoremap <C-v> m`<C-v>
vnoremap <esc> <esc>``
vnoremap y y``

" TODO: clean up <leader>l namespace
nnoremap <leader>lr :%s/<C-r><C-w>/
nnoremap <leader>lR :%s/<C-r><C-w>/<c-r><c-w>
nnoremap <silent><leader>gm :echom '=== Messages until ' . strftime("%H:%M:%S")
      \ . ' ======================='
      \ \| :silent Verbose messages<cr> \| :silent only \| :normal G <cr>
      \ \| :setlocal syntax=txt
      \ \| echom ''
      \ <cr>

" Easier change and replace word
nnoremap c* *Ncgn
nnoremap c# #NcgN
nnoremap cg* g*Ncgn
nnoremap cg# g#NcgN

nnoremap <leader>hW :execute 'Help ' . expand('<cWORD>')<cr>
nnoremap <leader>hh :execute 'Help ' . expand('<cword>')<cr>
vnoremap <leader>hh y:execute 'Help ' . escape(expand(@"), ' ')<cr>
nnoremap <leader>hp :call Help(expand('%:t:r'))<cr>

" Go to alternate file
nnoremap <leader>ga <c-^>

nnoremap <silent> <leader>gw :silent wall<cr>

" Replace selection
xnoremap gs y:%s/<C-r>"//g<Left><Left>
nnoremap gs :%s//g<Left><Left>

" ### Searching

" Show matching brackets
set showmatch

" Don't blink when matching
set matchtime=0

" Incremental search
set incsearch

" Highlight found text
" set hlsearch

" Toggle highlighting current matches
nmap <silent><c-c> :set hlsearch! hlsearch?<CR>

set nowildmenu
cnoremap <tab> <C-L><C-D>

set wildignorecase

set ignorecase

" Case insensitive search when all lowercase
set smartcase

" Case inferred by default
set infercase

" Do not wrap while searching
" set nowrapscan

" Switch window if it contains wanted buffer
set switchbuf=useopen

" Modlines might be dangerous
" see also securemodelines.vim
set modelines=0

if filereadable(g:vim.rc_local)
    execute "source " . g:vim.rc_local
endif

"### Debugging

" NOTE: Neobundle unsets these
" set verbosefile=/tmp/vim-debug.log
" set verbose=15

